name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: yarn install
      - run: yarn workspaces run all

      - uses: ./reference-to-cid
        with:
          reference: 0f28cbca43be232f524a17fd6db3b99e044b6bd5ba21055b286f59e472bde42f

      - uses: ./upload-dir
        with:
          dir: ./upload-dir/dist
